#!/bin/bash

build="$1"
filename="$2"

# Release
if [ "$build" == "release" ]; then
    nvcc -O2 -o ${filename%.*} $filename -I../../../../cutlass/include --gpu-architecture sm_80 --expt-relaxed-constexpr --use_fast_math

# Profile
elif [ "$build" == "profile" ]; then
    nvcc -O2 -lineinfo -o ${filename%.*} $filename -I../../../../cutlass/include --gpu-architecture sm_80 --expt-relaxed-constexpr
    if [ $? -eq 0 ]; then
      ncu --set full -f -o ${filename%.*} ${filename%.*}
      nsys profile -f true -o ${filename%.*} ${filename%.*}
    fi

# Debug
elif [ "$build" == "debug" ]; then
    nvcc -G -g -O0 -DDEBUG -o ${filename%.*} $filename -I../../../../cutlass/include --gpu-architecture sm_80 --expt-relaxed-constexpr

# Validate (Debug)
elif [ "$build" == "validate" ]; then
    nvcc -G -g -O0 -DDEBUG -DCPU_MATH_VALIDATION_ENABLED -o ${filename%.*} $filename -I../../../../cutlass/include --gpu-architecture sm_80 --expt-relaxed-constexpr

else
    echo "usage: $0 [debug|release|profile] filename"
    exit 1
fi
