#!/bin/bash

run_build() {
    echo -e "\n$2"
    ./build "$1" "$2"
}

if [[ "$1" != "release" && "$1" != "debug" && "$1" != "profile" && "$1" != "validate" ]]; then
  echo "usage: $0 [debug|release|profile|validate] filename"
  exit 1
fi

run_build $1 s1_gemm_naive.cu && ./s1_gemm_naive

run_build $1 s2_gemm_naive_templated.cu && ./s2_gemm_naive_templated

run_build $1 s3_gemm_coalesced2d.cu && ./s3_gemm_coalesced2d

run_build $1 s4_gemm_tiled.cu && ./s4_gemm_tiled

run_build $1 s5_gemm_mma.cu && ./s5_gemm_mma

run_build $1 s5_gemm_mma_slow.cu && ./s5_gemm_mma_slow
