#!/bin/bash

run_build() {
    echo -e "\n$2"
    ./build "$1" "$2"
}

run_build release s1_gemm_naive.cu && ./s1_gemm_naive

run_build release s2_gemm_naive_templated.cu && ./s2_gemm_naive_templated

run_build release s3_gemm_coalesced2d.cu && ./s3_gemm_coalesced2d

run_build release s4_gemm_tiled.cu && ./s4_gemm_tiled

run_build release s5_gemm_mma.cu && ./s5_gemm_mma

run_build release s5_gemm_mma_slow.cu && ./s5_gemm_mma_slow
