#!/bin/bash

build_run() {
    echo -e "\n$2"
    base_name="${2%.*}"
    ./build "$1" "$2" && ./$base_name
}

if [[ "$1" != "release" && "$1" != "debug" && "$1" != "profile" && "$1" != "validate" ]]; then
  echo "usage: $0 [debug|release|profile|validate] filename"
  exit 1
fi

build_run $1 s1_gemm_naive.cu

build_run $1 s2_gemm_naive_templated.cu

build_run $1 s3_gemm_coalesced2d.cu

build_run $1 s4_gemm_tiled.cu

build_run $1 s5_gemm_mma.cu

build_run $1 s5_gemm_mma_fast.cu

build_run $1 s6_gemm_smem_mma.cu
